#!/bin/sh -e
# Copyright 2021 Canoncial
# See LICENSE file for licensing details.

if [ -z "$VIRTUAL_ENV" -a -d venv/ ]; then
    . venv/bin/activate
fi

if [ -z "$PYTHONPATH" ]; then
    export PYTHONPATH="lib:src"
else
    export PYTHONPATH="lib:src:$PYTHONPATH"
fi

flake8 --ignore=W605
coverage run --source=src -m unittest -v "$@"
coverage report -m
